eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:4040/eureka/
    instance:
        ip-address: 127.0.0.1
        lease-renewal-interval-in-seconds: 10
        prefer-ip-address: true
management:
    security:
        enabled: false

spring:
    redis:
        host: 192.168.50.104
        port: 6379
zuul:
    debug:
        request: true
    include-debug-header: true
#内网连接nc映射
apiService:
    url: http://192.168.50.120:3101