eureka:
    client:
        serviceUrl:
            defaultZone: http://172.17.226.32:4040/eureka/
    instance:
#        instance-id: ${eureka.instance.ip-address}:${server.port}
        ip-address: 172.17.226.29
        preferIpAddress: true
server:
    port: 2911
spring:
    datasource:
        url: jdbc:mysql://rm-2zea5a578pf40fyea.mysql.rds.aliyuncs.com:3306/nongyequan
    redis:
        host: 172.17.226.32
        port: 6379
